### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by BTaskaya** [hakancelik96/coogger#2]
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/batuhan/coogger/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/batuhan/coogger/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/batuhan/coogger/.venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/batuhan/coogger/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/batuhan/coogger/.venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/batuhan/coogger/cooggerapp/models.py", line 6, in <module>
    from cooggerapp.views.tools import Topics,make_choices
  File "/home/batuhan/coogger/cooggerapp/views/tools.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
```

Requirements doesnt contain BS4

```
(.venv) batuhan@osman:~/coogger$ pip3 install -r requirements.txt 
Requirement already satisfied: Django==1.11.7 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: django-ckeditor==5.3.1 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: django-js-asset==0.1.1 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: djangorestframework==3.7.3 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Pillow==4.3.0 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pytz in ./.venv/lib/python3.5/site-packages (from Django==1.11.7->-r requirements.txt (line 1))
Requirement already satisfied: olefile in ./.venv/lib/python3.5/site-packages (from Pillow==4.3.0->-r requirements.txt (line 5))

```

**Comment by hakancelik96** [comment]
gözden kaçmış teşekkürler 🖐️

**Comment by BTaskaya** [comment]
Kapatılabilir.
